name: Update Changelog
on:
  push:
    branches:
      - main
permissions:
  contents: read
jobs:
  changelog:
    name: Conventional Changelog Action
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Conventional Changelog Action
        uses: TriPSs/conventional-changelog-action@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}